theme: jekyll-theme-cayman
title: "Rogier Krijnen"
description: Blog of Rogier Krijnen MSc.
markdown:    kramdown
highlighter: rouge
# mathjax: true

title: blog@RPKrijnen
email: r.p.krijnen@tudelft.nl
description: >- # this means to ignore newlines until "baseurl:"
  blog@RPKrijnen
baseurl: "/blog" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: rpkrijnen
github_username:  rpkrijnen

kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false
  auto_ids: true
  footnote_nr: 1
compress_html:
  clippings: all
  blanklines: true

defaults:
  - scope:
      path: "_posts"
    values:
      layout: "posts"
      theme: jekyll-theme-cayman

  # defaults:
  #  # _posts
  #  - scope:
  #      path: ""
  #      type: posts
  #    values:
  #      layout: single
  #      author_profile: true
  #      read_time: true
  #      comments: true
  #      share: true
  #      related: true
  #      mathjax: true